[build]
  command = """
  rustup install nightly --profile minimal && \
  cargo doc --no-deps --workspace --exclude=metrics-observer && cp -r target/doc _netlify_out
  """
  environment = { RUSTDOCFLAGS= "--cfg docsrs" }
  publish = "_netlify_out"

[[redirects]]
  from = "/"
  to = "/metrics"