[env]
RUST_TEST_THREADS = "1"
CARGO_MAKE_RUN_CODECOV = "true"
RUSTFLAGS = "-D warnings"
CARGO_FEATURES = "--no-default-features"

[tasks.format-stable]
command = "cargo"
args = ["fmt"]

[tasks.pre-verify-project]
dependencies = ["check-format", "clippy", "coverage-flow"]

[tasks.pre-coverage]
dependencies = ["test"]

[tasks.build-verbose]
description = "Runs the rust compiler with verbose output, with interpolated features."
category = "Build"
command = "cargo"
args = ["build", "--verbose", "${CARGO_FEATURES}"]

[tasks.test-verbose]
description = "Runs all available tests with verbose output, with interpolated features."
category = "Test"
command = "cargo"
args = ["test", "--verbose", "${CARGO_FEATURES}"]

[tasks.test]
description = "Runs all available tests, with interpolated features."
category = "Test"
command = "cargo"
args = ["test", "${CARGO_FEATURES}"]
